version: "3.3"
services:
  mongodb_container:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - "data:/data"

  mongo_express_container:
      image: mongo-express:latest
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=root
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=rootpassword
#        - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#        - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      depends_on:
          - mongodb_container
      ports:
          - "8888:8081"
volumes:
  data: